// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreManagementSystem.Data;

#nullable disable

namespace StoreManagementSystem.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260201152339_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreManagementSystem.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Books"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Office"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Audio"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Home&Garden"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Kitchen"
                        });
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(7,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 6,
                            Name = "Car Speakers",
                            Price = 15.49m,
                            Quantity = 57,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 7,
                            Name = "Herb Garden Planter Box",
                            Price = 49.99m,
                            Quantity = 60,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Name = "Metallica T-Shirt",
                            Price = 3.49m,
                            Quantity = 94,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 5,
                            Name = "Black Pen",
                            Price = 2.99m,
                            Quantity = 31,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Name = "Portable Bluetooth Headphones",
                            Price = 79.99m,
                            Quantity = 96,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Name = "Wireless Car Charger",
                            Price = 24.99m,
                            Quantity = 35,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 5,
                            Name = "100-Page Notebook",
                            Price = 2.49m,
                            Quantity = 77,
                            SupplierId = 7
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            Name = "Car Sunshade",
                            Price = 19.99m,
                            Quantity = 83,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 7,
                            Name = "Scented Candles",
                            Price = 19.99m,
                            Quantity = 49,
                            SupplierId = 9
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 7,
                            Name = "Cushion Covers",
                            Price = 35.99m,
                            Quantity = 27,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 1,
                            Name = "Mini Electric Kettle",
                            Price = 29.99m,
                            Quantity = 86,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 7,
                            Name = "Incense Holder",
                            Price = 14.99m,
                            Quantity = 76,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            Name = "Jogging Top",
                            Price = 5.99m,
                            Quantity = 18,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3,
                            Name = "Warm Knit Beanie",
                            Price = 19.99m,
                            Quantity = 78,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 1,
                            Name = "Samsung Galaxy Smartwatch",
                            Price = 249.99m,
                            Quantity = 11,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Name = "Gone Girl",
                            Price = 16.99m,
                            Quantity = 2,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 8,
                            Name = "Utensils Set",
                            Price = 4.49m,
                            Quantity = 81,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 1,
                            Name = "PC Microphone",
                            Price = 10.59m,
                            Quantity = 10,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 2,
                            Name = "Wrist Wrap",
                            Price = 4.99m,
                            Quantity = 60,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 5,
                            Name = "Pencil Set",
                            Price = 5.99m,
                            Quantity = 60,
                            SupplierId = 3
                        });
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            SupplierName = "Waters, Wolf and MacGyver"
                        },
                        new
                        {
                            SupplierId = 2,
                            SupplierName = "Bednar, Luettgen and Abernathy"
                        },
                        new
                        {
                            SupplierId = 3,
                            SupplierName = "Rippin and Sons"
                        },
                        new
                        {
                            SupplierId = 4,
                            SupplierName = "Pollich LLC"
                        },
                        new
                        {
                            SupplierId = 5,
                            SupplierName = "Schowalter, Kiehn and Rolfson"
                        },
                        new
                        {
                            SupplierId = 6,
                            SupplierName = "Hartmann-Jaskolski"
                        },
                        new
                        {
                            SupplierId = 7,
                            SupplierName = "Stanton-Cummerata"
                        },
                        new
                        {
                            SupplierId = 8,
                            SupplierName = "O'Keefe-Ryan"
                        },
                        new
                        {
                            SupplierId = 9,
                            SupplierName = "Bergnaum LLC"
                        },
                        new
                        {
                            SupplierId = 10,
                            SupplierName = "Donnelly-Kris"
                        });
                });

            modelBuilder.Entity("StoreManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Cart", b =>
                {
                    b.HasOne("StoreManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.CartItem", b =>
                {
                    b.HasOne("StoreManagementSystem.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreManagementSystem.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Order", b =>
                {
                    b.HasOne("StoreManagementSystem.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.OrderItem", b =>
                {
                    b.HasOne("StoreManagementSystem.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreManagementSystem.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Product", b =>
                {
                    b.HasOne("StoreManagementSystem.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreManagementSystem.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.User", b =>
                {
                    b.HasOne("StoreManagementSystem.Models.Supplier", "Supplier")
                        .WithMany("Users")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.Supplier", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("StoreManagementSystem.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
